CREATE TABLE QUESTIONS (
  ID    INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255)
);
CREATE TABLE SURVEY (
  ID              INT PRIMARY KEY AUTO_INCREMENT,
  TITLE           VARCHAR(255),
  DESCRIPTION     VARCHAR(255),
  CREATION_DATE   DATE,
  EXPIRATION_DATE DATE,
  LINK            VARCHAR(255)
  #   FOREIGN KEY (questions_id) REFERENCES QUESTIONS (id)
);
CREATE TABLE QUESTION_SURVEY (
  QUESTION_ID INT,
  SURVEY_ID   INT,
  CONSTRAINT FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(ID),
  CONSTRAINT FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY (ID)
);